### ISSUE TITLE
Rendering when episode terminates due to constraint violations

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/gym-electric-motor#10]
If an episode terminates due to constraint violations before the maximum number of steps is reached it has to be guaranteed that the render command covers the entire simulation time until the termination event. In particular, it could occur that the episode termination occurs very early before the render command is executed regularly the first time in a given episode. In this special case the render function should still be called to enable visualization.

**Comment by praneeth-b** [comment]
Implemented as part of issue #11

**Comment by pramodcm95** [comment]
the implementation seems to match the requirements specified in issue
