### ISSUE TITLE
Error in the labeling of plots

### ISSUE THREAD

**Issue by fbook98** [upb-lea/gym-electric-motor#127]
Hello, when plotting the currents i_a and i_e there is an error in the labeling of the plots.

![Time_Plots](https://user-images.githubusercontent.com/64723297/107348544-73df9200-6ac7-11eb-9f93-35c110d9bd66.png)

**Comment by atra94** [comment]
I think I already found the bug. I will fix it this evening and will push it to the current nightly and master branches.
