### ISSUE TITLE
Change default variable order in the dq-frame

### ISSUE THREAD

**Issue by max-schenke** [upb-lea/gym-electric-motor#16]
Coordinates in the dq-frame are given the "wrong" way round.

E.g. from the documentation of the Synchronous Motor:

> Args:
>             state: The current state of the motor. [**i_sq, i_sd**, epsilon]
>             omega: The mechanical load
>             u_qd: The input voltages [**u_sq, u_sd**]

To comply with the convention and minimize error potential, it should be changed to d before q: [u_d, u_q], [i_d, i_q].

**Comment by wallscheid** [comment]
Please also check with PMSM examples if order change inflects with execution.

**Comment by max-schenke** [comment]
It has been discussed in an internal meeting that changing the coordinate frame in the physical_system.py has priority over changing it in the electric_motors.py.

The order in physical_system.py is significant for the I/O of GEM in general, so changing it here will increase the usability as the momentary implemented qd ordering is prone to provoke errors.

Changing the order in electric_motors.py would probably increase code readability, but the casual user would not experience any improvement.

**Comment by pramodcm95** [comment]
qd re-ordering has been done in physical_systems.py and a quick review from @max-schenke  is completed.

**Comment by max-schenke** [comment]
Reordering in electric_motos.py will be done by me ASAP. 
(or maybe by @atra94 in case he is bored) 😄 
This should only concern the PMSM and the SynRM since the SCIM and DFIM are modelled in stator fixed alpha-beta coordinates.

A qualitative integration test should be performed afterwards to see if all the three-phase motors run in the desired way.

**Comment by max-schenke** [comment]
Correction of dq coordinates has been done in electric_motors.py. The unit tests have been changed accordingly. I would like @atra94 to take a second look at the differential equations of the PMSM and SynRM (including the Jacobians).

As the GEM docs also needs to be changed to the new order of the dq coordinates, I will leave this Issue open and will not file a pull request yet. I will change the docs ASAP (hopefully tomorrow) and close this Issue afterwards.

**Comment by max-schenke** [comment]
Docs have been updated to show d-axis before q-axis. As soon as the differential equations and maybe the docs have been reviewed by @atra94 we can wrap up this issue.
