### ISSUE TITLE
Plot problem

### ISSUE THREAD

**Issue by mgdearaujo** [upb-lea/gym-electric-motor#164]
Hello, I'm now studying the GEM for my last work at School. And I'm having trouble plotting the example code. At the Keras example and the classic control.
![image](https://user-images.githubusercontent.com/92227109/136669519-193f3717-3109-4322-8880-c006734618a4.png)

**Comment by mgdearaujo** [comment]
Hi @atra94,
I realize that the minimum number of steps is about 10000. I was putting 1000 steps and it wasn`t showing anything.

**Comment by romeshprasad** [comment]
Hi, @atra94 
I am having a similar issue when trying to execute the reinforcement learning example on google collab  "Cont-SC-SeriesDc-v0".

If I train the agent for 15000 or fewer steps I get plots, but the plots are half empty.
But, if I increase the steps beyond 15000, I get an empty plot.
Additionally, if I reduce from 15000 plots to 10000 plots I get plots that cover the entire space, but between 15000 to 10000 only the right side is filled. 

This is the snap of code 
![test_train error](https://user-images.githubusercontent.com/56453677/145644691-c1c49046-82a5-4e17-a827-7efee9b7dabe.JPG)

This is the plot for train steps below 15000.
![image](https://user-images.githubusercontent.com/56453677/145645304-aeef7c64-01d1-4876-9fb6-6d97115749d2.png)

For 15000 and above the plot is empty as shown in the image posted by @mgdearaujo.
