### ISSUE TITLE
gym will change the seeding of environments

### ISSUE THREAD

**Issue by atra94** [upb-lea/gym-electric-motor#183]
I noticed that the seeding of environments (`` env.seed(seed) `` )will be integrated into the ``env.reset()`` method in the next release of gym.
For a few versions also the old seeding will stay compatible (with depreciation warning). 

Nonetheless, also gem has to adapt to this interface, soon.

**Comment by wkirgsn** [comment]
gymnasium API was adopted in GEM v2.0.0
