### ISSUE TITLE
Do you have pytorch version of RL controllers?

### ISSUE THREAD

**Issue by vapemaster-kz** [upb-lea/gym-electric-motor#185]
Hi, I was wondering if you had a pytorch version of RL controllers? I am specifically interested in DDPG_PMSM_CURRENT controller.

**Comment by atra94** [comment]
Hi, 

currently there is no pure pytorch RL controller example in GEM. 
However, [stable baselines 3](https://github.com/DLR-RM/stable-baselines3) is built upon pytorch.  In GEM there is also a [stable baselines GEM example](https://github.com/upb-lea/gym-electric-motor/blob/master/examples/reinforcement_learning_controllers/stable_baselines3_dqn_disc_pmsm_example.ipynb).

If you find any PyTorch RL Controller that is compliant with the Gym-Interface it should require only minor changes to train on a gym-electric-motor environment.
