### ISSUE TITLE
Can you email me, please ?

### ISSUE THREAD

**Issue by vapemaster-kz** [upb-lea/gym-electric-motor#186]
Dear @atra94. 

If I am not bothering you much, could you please email me on: _**CENSORED**_ . I just had a couple of questions regarding the project.

**Comment by atra94** [comment]
Hi,

thanks for your interest on GEM.

In your own interest, I deleted your email address from this site. I would prefer that you post your questions here, even if there are multiple questions. 

A good starting point for the work with GEM is the [cookbook](https://github.com/upb-lea/gym-electric-motor/blob/master/examples/environment_features/GEM_cookbook.ipynb).
