### ISSUE TITLE
DDPG examples require unofficial keras-rl2 hotfixes

### ISSUE THREAD

**Issue by wkirgsn** [upb-lea/gym-electric-motor#19]
To be fixed by either
* Implementing own DDPG algo in examples folder
* Use a different neural network framework than keras-rl2
* update setup.py  to keras_rl2 and annotate readme in examples on how to apply fixes to keras-rl2

**Comment by wallscheid** [comment]
also applies to dqn example

**Comment by wallscheid** [comment]
> 
> 
> To be fixed by either
> 
>     * Implementing own DDPG algo in examples folder
> 
>     * Use a different neural network framework than keras-rl2
> 
>     * update setup.py  to keras_rl2 and annotate readme in examples on how to apply fixes to keras-rl2

In the nightly branch, the hotfix (third bullet point) is now included.
