### ISSUE TITLE
incompatibility with gym >0.24.0

### ISSUE THREAD

**Issue by atra94** [upb-lea/gym-electric-motor#195]
OpenAI has released new versions 0.24.0 and 0.24.1 of gym recently.

One new feature is a "PassiveEnvChecker" that checks multiple environment properties (e.g. action-space, observation-space etc.)

There seems to be a bug (in gym) when checking for our tuple-observation spaces. Therefore, GEM is currently incompatible with every gym-version from 0.24.0 on.

I will investigate this error more in depth and post also an issue to the gym-repo if the bug is really in the gym-code.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, Im from the gym dev team. 
In v24, there was a number of bugs in the passive environment checker.
In v25, all of these bugs are fixed, could you check that this doesn't cause unexpected results

To test you can run `gym.utils.env_checker.check_env`

**Comment by pseudo-rnd-thoughts** [comment]
I just saw https://github.com/upb-lea/gym-electric-motor/issues/183 as well. 
If you need any help updating to the new API, there is a number of changes in v25 and v26 (in the future).
Join the gym discord server (https://discord.gg/nHg2JRN489) and contact myself (Pseudo-Rnd)

**Comment by PaParaZz1** [comment]
Is there some exact plans to upgrade gym version?

**Comment by wkirgsn** [comment]
We have this issue on our backlog, and we will fix it in near future

**Comment by PaParaZz1** [comment]
> We have this issue on our backlog, and we will fix it in near future

Thank you! I am the developer of [DI-engine](https://github.com/opendilab/DI-engine), looking for some interesting applications to apply advanced DRL algorithms and collect meaningful demonstrations. Are you willing to develop more examples and benchmark results abour your repo together, or any other ideas?

**Comment by wkirgsn** [comment]
`>>> env_checker.check_env(gem.make("Cont-CC-SCIM-v0"))`

```
AssertionError: The obs returned by the `reset()` method length is not same
 as the observation space length, obs length: 14, space length: 2
```

`gym-0.26.2`  and `gym-electric-motor-1.1.0`

**Comment by pseudo-rnd-thoughts** [comment]
In Gym v0.26, there was a large number of changes to the API - https://gymnasium.farama.org/content/migration-guide/
In reset, the return type expected is a tuple of the observation and info. 
As this environment has a tuple with length 2, then it passed the first check but failed the second that the observation is contained within the observation space. You need to modify the `reset` and `step` functions to match gym v0.26 API

**Comment by wkirgsn** [comment]
thanks for the hint, I will look into it

**Comment by wkirgsn** [comment]
gymnasium API was adopted in GEM v.2.0.0
