### ISSUE TITLE
Flat velocity plot for scim_ideal_grid_simulation.py

### ISSUE THREAD

**Issue by jose-otero-rodriguez** [upb-lea/gym-electric-motor#199]
Hi:
Oddly, this script is not working right now, the speed estimation is flat. Any clue about how to solve this?
Thanks 
![Figure_1](https://user-images.githubusercontent.com/108660374/194534930-2867bb12-2123-48e6-85b6-ccb88bca5ecb.png)

**Comment by max-schenke** [comment]
Apparently we changed the default mechanical load along the way to have a fixed speed. Therefore we now need to manually set a mechanical load that sets a variable speed.

This issue should be taken care of in the master and nightly branch now. Please report if the issue was resolved on your end.

**Comment by jose-otero-rodriguez** [comment]
The updated script works as expected.
Thanks
![Figure_1](https://user-images.githubusercontent.com/108660374/195055401-da8c965d-1dfa-4e84-aa72-c9ee6e7764d9.png)
