### ISSUE TITLE
Limit values for PMSM motor appear to be a peak to peak value vs an amplitude value

### ISSUE THREAD

**Issue by jmailloux** [upb-lea/gym-electric-motor#204]
Documentation for phase voltage limit states that it should be an amplitude.  Yet, if it is set to say 70V, the voltage waveforms (ua, ub, uc) won't go above 35V in amplitude.

**Comment by wkirgsn** [comment]
Hey, thanks for the heads-up, we will change the documentation accordingly

**Comment by jmailloux** [comment]
Thanks @wkirgsn .  If you are going to update the documentation, one other question I had - it isn't clear from the documentation whether ua, ub, uc is phase voltage (phase to neutral), line voltage (phase to phase), or terminal voltage (phase to ground).
