### ISSUE TITLE
Typo in the calculation of the decoupling 

### ISSUE THREAD

**Issue by MarvinMeyer** [upb-lea/gym-electric-motor#209]
Hey,

I have found a typo in the calculation of the decoupling of the q-component:

https://github.com/upb-lea/gym-electric-motor/blob/b43b9a706d4163aa838bea4c6e81900ddc8eb4aa/examples/classic_controllers/controllers/foc_controller.py#L95-L100

In line 99 it should be `self.limit[self.i_sd_idx]` instead of self.limit[self.u_sd_idx].

**Comment by wkirgsn** [comment]
PR #211 merged into nightly
