### ISSUE TITLE
Hi, We are using the GEM library for testing the functionality of PMSM as a part of our undergraduate project.

### ISSUE THREAD

**Issue by Priyadharshan2001** [upb-lea/gym-electric-motor#228]
We do not plan to use either motor control or the RL part of the library , however we would like to use it only for PMSM testing.

For the same purpose, we would like to make changes to the circuit implementation of PMSM.
We are referring to the documentation from this site: https://upb-lea.github.io/gym-electric-motor/parts/physical_systems/electric_motors.html#gym_electric_motor.physical_systems.electric_motors.PermanentMagnetSynchronousMotor
and also the documents referred to in it.

As our understanding of the PY code goes, the motor parameters passed to the PMSM function consist of the following:
'p': number of poles
 'l_d': inductance D-component
 'l_q':  inductance Q-component ,
 'j_rotor': Moment of inertia of the rotor
'r_s': 0.stator resistance
We would like to know the exact function which implements the PMSM circuit.
We would also like to know how to include mutual inductance in these motor parameters and change the PMSM circuit.
We need to include mutual inductance of the stator windings in the circuit and we also prefer to  make changes to the mutual inductance between the stator windings.

Request you to provide us this information in order to complete our project.

Thanks,

**Comment by wkirgsn** [comment]
Hi, there is a stripped-down environment for a PMSM with differential inductances support at 

https://github.com/ExcitingSystems/exciting-environments/blob/main/exciting_environments/saturated_pmsm/saturated_pmsm_env.py 

Maybe this helps for the time being
