### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by BucurCosmin** [upb-lea/gym-electric-motor#3]
I'm trying to install the package but I get:
import gym_electric_motor as gem
ModuleNotFoundError: No module named 'gym_electric_motor'

**Comment by jcook3701** [comment]
I was having the same issues as it appears that the pip installation is broken.  This is what worked for me:
1. Source into appropriate virtual python env. 
2. pip install gym-electric-motor - as this installs all dependencies. 
3. pip uninstall gym-electric-motor
4. pip uninstall gym
5. git clone https://github.com/upb-lea/gym-electric-motor.git
6. cd gym-electric-motor
7. python setup.py install

**Comment by BucurCosmin** [comment]
After doing for 5 or 6 times all the 3 ways of installing, it's working

**Comment by wkirgsn** [comment]
I can confirm that the pip package seems broken. Diving deeper into it

**Comment by wkirgsn** [comment]
Found the bug.
The setup.py did not specify this line:

`packages=setuptools.find_packages()`

Incremented repo version to 0.0.4, now you should be able to pip install into your environment.

As a side note, be aware where you pip install GEM into: [Pitfalls in pip installs](https://stackoverflow.com/questions/32680081/importerror-after-successful-pip-installation
)

if "which python" and "which pip" are different, make sure to call "python -m pip gym-electric-motor" to install into your desired environment.
