### ISSUE TITLE
Pip install fails with Python 3.8

### ISSUE THREAD

**Issue by wkirgsn** [upb-lea/gym-electric-motor#39]
With python 3.8, pip install fails due to PyQT5's dependency to "sip".
Pip can't find a version that covers all version constraints of sip.

**Comment by wallscheid** [comment]
Should we maybe label the usability of the toolbox with respect to the usual Python versions? Such it becomes clear to the usage directly what Python versions work?

**Comment by RohithCharanD** [comment]
Yes,That might make the user life easier.We have a requirements.txt file. We can add few more comments to that such as compatible python versions and pip versions etc.,

**Comment by wallscheid** [comment]
Short test in seperate branch to monitor if QT5 is not needed anymore.

**Comment by wallscheid** [comment]
Requires clean up QT5 within a couple of project files. Delete QT5 imports and test if it works without import.

**Comment by wkirgsn** [comment]
PyQT5 must be removed from requirements.txt.
This will result in moduleNotFoundErrors cos of imports of PyQt5.
In particular, tests.conf has such an import that must be deleted.

**Comment by praneeth-b** [comment]
Deleted pyqt dependencies in tests/conf.py.
removed pyqt from requirements.txt  and tested GEM toolbox on a fresh conda env with python 3.8.
the example scripts run without issues.

**Comment by wkirgsn** [comment]
PR merged
