### ISSUE TITLE
[v0.2.1] Example script: "pi_series_omega_control.py"  fails 

### ISSUE THREAD

**Issue by praneeth-b** [upb-lea/gym-electric-motor#40]
Maybe a reset() is not triggered in the environment upon episode termination due to a violation. Exception is thrown in the during the control.

> Traceback (most recent call last):
  File "/home/praneeth/projects/gym-electric-motor/examples/pi_series_omega_control.py", line 39, in <module>
    (state, reference), reward, done, _ = env.step(action)
  File "/home/praneeth/projects/gym-electric-motor/gym_electric_motor/core.py", line 228, in step
    raise Exception('A reset is required before the environment can perform further steps')
Exception: A reset is required before the environment can perform further steps

**Comment by wallscheid** [comment]
@praneeth-b : Could you please re-check if that is still the case with the master and/or nightly branch? For me both works fine.
