### ISSUE TITLE
On_off_Controller with MotorDashboard plotted_variables='all' is not plotting anything

### ISSUE THREAD

**Issue by wkirgsn** [upb-lea/gym-electric-motor#44]
Running pi_series_omega_control.py with a MotorDashboard(plotted_variables='all', visu_period=1) and with an on_off_controller, is not plotting any progress on the diagrams.

Running the script with another controller or with a certain set of plotted_variables will work normally though.

**Comment by wallscheid** [comment]
New Visualization is going to be tested with examples to check if this buf is still there.

**Comment by atra94** [comment]
Closed with PR.
