### ISSUE TITLE
Documentation stray inductance

### ISSUE THREAD

**Issue by GitPascalP** [upb-lea/gym-electric-motor#45]
documentation of Inductionmotor stray inductance in doctrings and online documentation does not match with dictionary keys
![grafik](https://user-images.githubusercontent.com/56597649/84266240-73e85600-ab24-11ea-9ca4-b43eecc2a0a3.png)

![grafik](https://user-images.githubusercontent.com/56597649/84266192-5dda9580-ab24-11ea-8f18-bd12a63bfdb1.png)

**Comment by max-schenke** [comment]
Will be corrected altogether with #16 since I am changing the docs anyway. 
This fix will therefore be included in the Issue16 branch.

**Comment by max-schenke** [comment]
I decided to go with l_sigs and l_sigr to be consistent to the [lecture notes of _Controlled Three-Phase Drives_ (PDF)](https://ei.uni-paderborn.de/fileadmin/elektrotechnik/fg/lea/Lehre/GDA/Dokumente/Geregelte_Drehstromantriebe_DE_EN.pdf). The unit tests have been changed accordingly. This issue can be closed as soon as the pull request for Issue#16 is finished.
