### ISSUE TITLE
Extensions to graphics output

### ISSUE THREAD

**Issue by wallscheid** [upb-lea/gym-electric-motor#55]

**Comment by wkirgsn** [comment]
line colors do not match with matplotlib.styles but rather are predetermined. This does not fit visually.

**Comment by atra94** [comment]
Topics for the further development of the motor dashboard in the next sprint could be the following:

- Include plots that are episode based. (One point per episode and not one point per step). A good introductory example could be a mean reward per episode plot.
- Shift redundant code of the step based plots (StatePlot RewardPlot ActionPlot) into a common base class
- Develop a clean interface to configure the plots. Ideally, common attributes in different plots (e.g. x-Axis length) should be set only once.
- (Optional:) Add the possibility to plot multiple states per plot. (e.g. all currents or all actions into one graph)
- Investigate

**Comment by praneeth-b** [comment]
- code improved by moving repeated code to a base class : 'MotorDashboardPlot'
-Configuring of common parameters done only once in the current implementation
- Implemented episode based plot- 'Mean episode reward' in a separate figure. A working implementation made. Certain aesthetic improvements and cleanup pending.

![Screenshot from 2020-07-17 16-03-25](https://user-images.githubusercontent.com/62220045/87794991-bbf74880-c847-11ea-952b-6cc3d16ac711.png)

**Comment by wallscheid** [comment]
Side note for further implementations: The new additional mean reward plot is currently only available on a per episode basis. However, for the general motor control problem it would be also fine to perform the control task on a continuing fashion without any episodes (except terminations due to constraints). A future extension to the mean reward plotter should therefore be a moving average style plot with a configurable moving average filter (plotted on the per-step grid e.g. in the same sub-plot as the instanous reward).
