### ISSUE TITLE
Default Voltage Supply values are being overwritten in physical_systems.py

### ISSUE THREAD

**Issue by XyDrKRulof** [upb-lea/gym-electric-motor#62]
Currently the default settings in voltage supplies for the supply voltage are being overwritten by this code in physical_systems.py. The critical part is in the else-block:

```       
       if 'u_sup' in kwargs.keys():
            u_sup = kwargs['u_sup']
        else:
            u_sup = self._electrical_motor.limits['u']
        self._supply = instantiate(vs.VoltageSupply, supply, u_nominal=u_sup, tau=tau, **kwargs)
```

It should be discussed if this behavior is wanted. For example the default values suggested in issue #48 for the new AC supplies are being overwritten by this code.

**Comment by wallscheid** [comment]
I believe it is pretty Ok, since it is an easy solution to re-use the limit voltage of the motor as the supply voltage if the user is not providing the supply voltage value during initialization. Hence, I would suggest closing the issue.
