### ISSUE TITLE
ConstantSpeedLoad not working with the new load_initializer argument

### ISSUE THREAD

**Issue by XyDrKRulof** [upb-lea/gym-electric-motor#76]
The ConstantSpeedLoad class is currently not working with the new load_initializer argument. It is overwriting MechanicalLoad's init and reset and is not forwarding the initializer_params to the super class.

For more information see internal discussions in Teams.

**Comment by XyDrKRulof** [comment]
Hotfix available in branch issue_#76. No tests written for it (yet)

**Comment by GitPascalP** [comment]
A possible fix is now available in issue_9_30_fix with the basic tests. The init is now possible by giving the ConstantSpeedLoad (or external load) the initializer as an Argument.

**Comment by max-schenke** [comment]
The corresponding branch has been merged to nightly. Thank you for your contributions!
