### ISSUE TITLE
Unexpected multiplication of input voltage

### ISSUE THREAD

**Issue by max-schenke** [upb-lea/gym-electric-motor#83]
I tried to run some tests with the ` DcSeriesDisc-v1` environment. This env uses a one-quadrant converter which is (supposed to be) controllable by actions `0` (switch is off) and `1` (switch is on).

Action `0`: I get what I expect
`(x, r), reward, done, _ = env.step(0)`
<img src="https://user-images.githubusercontent.com/61693487/90605400-940c5380-e1fe-11ea-9880-7b1e661ee559.png" width="350"/>

Action `1`: I also get what I expect
`(x, r), reward, done, _ = env.step(1)`
<img src="https://user-images.githubusercontent.com/61693487/90605530-c453f200-e1fe-11ea-8c64-7eca0f349930.png" width="350"/>

I verified that these 420 V is in fact the supply voltage:
<img src="https://user-images.githubusercontent.com/61693487/90605628-e9486500-e1fe-11ea-8e9e-e2887fedc779.png" width="350"/>

So far so good. But now I accidentally commit a mistake and apply an action that is (/ should be) unavailable, e.g. 5:

Action `5`: I get five times more voltage than the supply offers... energy shortage solved?^^
`(x, r), reward, done, _ = env.step(5)`
<img src="https://user-images.githubusercontent.com/61693487/90605838-33314b00-e1ff-11ea-94ff-c5340804df5a.png" width="350"/>
<img src="https://user-images.githubusercontent.com/61693487/90605858-39272c00-e1ff-11ea-98ee-c49715c92be1.png" width="350"/>

Action `-5`: I have no idea what this could be
`(x, r), reward, done, _ = env.step(-5)`
<img src="https://user-images.githubusercontent.com/61693487/90606902-c454f180-e200-11ea-8ed5-f8e1238d310d.png" width="350"/>
<img src="https://user-images.githubusercontent.com/61693487/90606929-ce76f000-e200-11ea-95a9-d7710a1cf3ae.png" width="350"/>

This even works for non-integer inputs. The environment should only accept actions `0` and `1`, the other inputs should not be processed in the presented way. Please verify these findings before fixing.

**Comment by max-schenke** [comment]
Solution approach in respective issue branch (issue_83).
Added an assertion that monitors whether the discrete converters are receiving valid action signals.
E.g.:
`AssertionError: The selected action 7 is not a valid element of the action space Discrete(4).`
`AssertionError: The selected action -1 is not a valid element of the action space Discrete(2).`
`AssertionError: The selected action 3.141592653589793 is not a valid element of the action space Discrete(8).`

**Comment by wallscheid** [comment]
@max-schenke : thanks for the bug fixing!

**Comment by max-schenke** [comment]
done
