### ISSUE TITLE
Clean Up Branches

### ISSUE THREAD

**Issue by atra94** [upb-lea/gym-electric-motor#92]
There are a lot of outdated, dead branches. I would please everyone to check your own branches for necessity. If there is and will be no Pull-Request anymore, they might be deleted. You can comment here, which branches I can delete for you or delete them by yourself.

**Comment by XyDrKRulof** [comment]
I will continue to use the branch issue_#70 for the feature engineering task until sprint #4 for the summer semester project group ends. So please do not delete it until after that.

**Comment by wkirgsn** [comment]
obsolete working package
