### ISSUE TITLE
High-performance tuning of DQN implementation

### ISSUE THREAD

**Issue by GitPascalP** [upb-lea/gym-electric-motor#95]
Tuning DQN implementation with:

- Feature engineering (observables, reward signal during learning)
- Hyperparameter optimization (toolbox choice on your own -> workstation) 

The optimization of the implementation should happen with:
- MAE as reward signal remains for test case
- All motor states should be randomly initialized at the start of one training episode (exploring starts)

**Comment by wkirgsn** [comment]
obsolete working package
